spring.datasource.admin.username=admin
spring.datasource.admin.password=hacker

spring.datasource.application.username=application
spring.datasource.application.password=hacker

# Enabling H2 Console
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

vulnerableapp.email.base-url=http://localhost
