spring.datasource.admin.username=${DB_ADMIN_USERNAME}
spring.datasource.admin.password=${DB_ADMIN_PASSWORD}

spring.datasource.application.username=application
spring.datasource.application.password=${DB_APP_PASSWORD}

spring.h2.console.enabled=false
spring.h2.console.settings.web-allow-others=false

spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
vulnerableapp.email.base-url=${APP_BASE_URL}
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN
