DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    department VARCHAR(100) NOT NULL,
    salary INT NOT NULL,
    social_security_number VARCHAR(20) NOT NULL
);

GRANT SELECT ON EMPLOYEES TO application;
